runtime: php72

handlers:
# Serve a directory as a static resource.
- url: /css
  static_dir: css
  
- url: /css/(.*\.(css)) 
  static_files: css/\1
  upload: css/(.*\.(css))
  
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$

# Serve your app through a front controller at index.php or public/index.php.
- url: .*
  script: auto
